### ISSUE TITLE
Error in process_tracks

### ISSUE THREAD

**Issue by naarkhoo** [renozao/NMF#35] opened 2015-05-25 15:45 UTC
I am puzzled how to fix the following error,
basically, I do something as following wotj R  3.2.0  amd NMF 0.20.5

NMF.models <- nmf(m.2, seq(k.min, k.max + 1, k.incr), nrun = number_of_runs, method="brunet", seed=9876)
consensusmap(NMF.models)

Error in process_tracks(x, tracks, annRow, annCol) : 
  Invalid special annotation track name ['basis:', 'consensus:', 'silhouette:']. Should partially match one of 'basis:', 'consensus:', 'silhouette:'. 

I was using this code/library a year ago and I don't think, I have this problem back then !

**Comment by renozao** [comment] 2015-05-25 22:19
This is a duplicate of #33 and http://lists.r-forge.r-project.org/pipermail/nmf-user/2015/000045.html.
It is due to the latest update of  ``stringr``.
A fix is on its way to CRAN.
If really in a rush it is also available in the master branch. Install with:

```R
source('http://renozao.github.io/repotools/install.R')
library(repotools)
# latest development version
install.pkgs('NMF', quick = TRUE)
```

**Closed by renozao** 2015-05-25 22:19 UTC
